server:
  port: 8000
  fetcher:
    timeout: 30s

solver:
  nodes:
    - http://localhost:3000
  timeout: 90s

proxy:
  urls:
    - http://username:password@host:port

redis:
  address: localhost:6379
  password: redis
  db: 1

cache:
  enabled: true
  ttl: 5m

rate_limit:
  max_rps_per_domain: 5